ACCESS_TOKEN_ENDPOINT = "api/v1/security/login"
CSRF_TOKEN_ENDPOINT = "api/v1/security/csrf_token"
DASHBOARD_ENDPOINT = "api/v1/dashboard/"
DATASET_ENDPOINT = "api/v1/dataset/"
CHART_ENDPOINT = "api/v1/chart/"
IMPORT_ENDPOINT = "api/v1/dashboard/import"
